[package]
name = "thunderduck-core"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
duckdb.workspace    = true
dashmap.workspace   = true
tokio.workspace     = true
sqlparser.workspace = true
java_regex.workspace = true
unicode-general-category.workspace = true
serde_json.workspace = true
tracing.workspace   = true
